# Generated by Django 5.1.6 on 2025-03-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_sessions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontimeslot',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sessiontimeslot',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
