# Generated by Django 5.1.6 on 2025-03-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_sessions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesession',
            name='needs_transportation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidatesession',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
