# Generated by Django 5.1.6 on 2025-03-25 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_sessions', '0003_sessiontimeslot_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontimeslot',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
