# Generated by Django 5.1.6 on 2025-04-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate_sessions", "0004_availabilityinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatesection",
            name="imported_availability_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="IDs of faculty availability submissions that have been imported",
                null=True,
            ),
        ),
    ]
