# Generated by Django 5.1.6 on 2025-03-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_sessions', '0004_alter_sessiontimeslot_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontimeslot',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
