# Generated by Django 5.1.6 on 2025-04-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_sessions', '0004_formfield_formfieldoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='fields',
            field=models.JSONField(default=list),
        ),
    ]
