# Generated by Django 5.1.6 on 2025-04-01 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_sessions', '0005_alter_form_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='fields',
        ),
    ]
