# Generated by Django 5.1.6 on 2025-04-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_sessions', '0006_remove_form_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formsubmission',
            unique_together=set(),
        ),
    ]
