# Generated by Django 5.1.6 on 2025-04-01 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_sessions', '0007_alter_formsubmission_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='type',
        ),
        migrations.AddField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('date_range', 'Date Range')], default=8, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='candidate_sessions.form'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
