# Generated by Django 5.1.6 on 2025-04-01 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_sessions', '0008_remove_formfield_type_formfield_field_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='field_type',
        ),
        migrations.AddField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes'), ('date', 'Date')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='candidate_sessions.form'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='label',
            field=models.CharField(max_length=200),
        ),
    ]
