# Generated by Django 5.1.6 on 2025-04-08 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_sessions', '0009_remove_formfield_field_type_formfield_type_and_more'),
    ]

    operations = [
    ]
