# Generated by Django 5.1.6 on 2025-04-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_sessions', '0010_seed_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='form_version',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('date_range', 'Date Range')], max_length=20),
        ),
    ]
