# Generated by Django 5.1.6 on 2025-04-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="room_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
