# Generated by Django 5.1.6 on 2025-04-09 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_room_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="room_number",
        ),
    ]
