# Generated by Django 5.1.6 on 2025-04-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_room_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="room_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Room Number/Office Location",
            ),
        ),
    ]
