# Generated by Django 5.1.6 on 2025-04-15 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_has_completed_setup"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_title", models.CharField(max_length=200)),
                ("current_department", models.CharField(max_length=200)),
                ("current_institution", models.CharField(max_length=200)),
                ("research_interests", models.TextField()),
                ("cell_number", models.CharField(max_length=20)),
                (
                    "travel_assistance",
                    models.CharField(
                        choices=[
                            (
                                "all",
                                "Yes, I will need help with ALL travel arrangements",
                            ),
                            (
                                "some",
                                "Yes, I will need help with SOME of my travel arrangements",
                            ),
                            (
                                "none",
                                "No, I will book ALL travel arrangements and will submit for reimbursement",
                            ),
                        ],
                        max_length=10,
                    ),
                ),
                ("passport_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField()),
                ("country_of_residence", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("prefer_not_to_say", "Prefer not to say"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "gender_custom",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("preferred_airport", models.CharField(max_length=200)),
                ("frequent_flyer_info", models.TextField(blank=True)),
                ("known_traveler_number", models.CharField(blank=True, max_length=100)),
                ("talk_title", models.CharField(max_length=300)),
                ("abstract", models.TextField()),
                ("biography", models.TextField()),
                ("headshot", models.ImageField(upload_to="candidate_headshots/")),
                ("videotape_permission", models.BooleanField(default=False)),
                ("advertisement_permission", models.BooleanField(default=False)),
                ("food_preferences", models.JSONField(default=list)),
                ("dietary_restrictions", models.JSONField(default=list)),
                ("extra_tours", models.BooleanField(default=False)),
                ("preferred_faculty", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("has_completed_setup", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
