# Generated by Django 5.1.6 on 2025-04-15 05:49

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_candidateprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="headshot",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.headshot_path
            ),
        ),
    ]
