# Generated by Django 5.1.6 on 2025-04-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_candidateprofile_headshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="advertisement_permission",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="extra_tours",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="videotape_permission",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
    ]
