# Generated by Django 5.1.6 on 2025-04-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_candidateprofile_advertisement_permission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="extra_tours",
            field=models.CharField(
                choices=[
                    ("Campus Tour", "Campus Tour"),
                    ("Community Tour w/Realtor", "Community Tour w/Realtor"),
                    ("Not at this time", "Not at this time"),
                ],
                default="Not at this time",
                max_length=50,
            ),
        ),
    ]
