# Generated by Django 5.1.6 on 2025-04-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_candidateprofile_extra_tours"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="preferred_visit_dates",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
