# Generated by Django 5.1.6 on 2025-04-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_candidateprofile_preferred_visit_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="available_for_meetings",
            field=models.BooleanField(
                default=True,
                help_text="Whether this staff member can be requested for meetings by candidates",
            ),
        ),
    ]
